### ISSUE TITLE
C50 Module

### ISSUE THREAD

**Issue by RyanMcBerg** [CodeSpaceHQ/MENGEL#94]
This module will train a dataset against the c50 algorithm and R and test it against a testing dataset.

**Comment by ASAAR** [comment]
@RyanMcBerg do we have an estimate for this?

**Comment by ZakeryFyke** [comment]
Issue has been ice boxed for now due to issues communicating between Python and R. More research into the subject will be necessary.

**Comment by ghost** [comment]
This is no longer an issue.
